import type { Metadata } from "next";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import HeaderNav from "@/components/headerNav";
import { CartProvider } from "@/context/cartContext";

export const metadata: Metadata = {
  title: "Baemin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="w-full h-fit">
        <HeaderNav />
        <AntdRegistry>
          <CartProvider>{children}</CartProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
